//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dorbit.Framework.Send
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Dorbit.Framework.Send.SendSoap")]
    public interface SendSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSimpleSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.SendSimpleSMSResponse> SendSimpleSMSAsync(Dorbit.Framework.Send.SendSimpleSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSimpleSMS2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.SendSimpleSMS2Response> SendSimpleSMS2Async(Dorbit.Framework.Send.SendSimpleSMS2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.SendSmsResponse> SendSmsAsync(Dorbit.Framework.Send.SendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWithDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.SendWithDomainResponse> SendWithDomainAsync(Dorbit.Framework.Send.SendWithDomainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsPrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.GetSmsPriceResponse> GetSmsPriceAsync(Dorbit.Framework.Send.GetSmsPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.GetCreditResponse> GetCreditAsync(Dorbit.Framework.Send.GetCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.GetDeliveryResponse> GetDeliveryAsync(Dorbit.Framework.Send.GetDeliveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDelivery2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.GetDelivery2Response> GetDelivery2Async(Dorbit.Framework.Send.GetDelivery2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMultiDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.GetMultiDeliveryResponse> GetMultiDeliveryAsync(Dorbit.Framework.Send.GetMultiDeliveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMultiDelivery2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.GetMultiDelivery2Response> GetMultiDelivery2Async(Dorbit.Framework.Send.GetMultiDelivery2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.GetDeliveriesResponse> GetDeliveriesAsync(Dorbit.Framework.Send.GetDeliveriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveries2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.GetDeliveries2Response> GetDeliveries2Async(Dorbit.Framework.Send.GetDeliveries2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveries3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.GetDeliveries3Response> GetDeliveries3Async(Dorbit.Framework.Send.GetDeliveries3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInboxCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.GetInboxCountResponse> GetInboxCountAsync(Dorbit.Framework.Send.GetInboxCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMessages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.getMessagesResponse> getMessagesAsync(Dorbit.Framework.Send.getMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendByBaseNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.SendByBaseNumberResponse> SendByBaseNumberAsync(Dorbit.Framework.Send.SendByBaseNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendByBaseNumber2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.SendByBaseNumber2Response> SendByBaseNumber2Async(Dorbit.Framework.Send.SendByBaseNumber2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendByBaseNumber3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.SendByBaseNumber3Response> SendByBaseNumber3Async(Dorbit.Framework.Send.SendByBaseNumber3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendByBaseNumber4", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.SendByBaseNumber4Response> SendByBaseNumber4Async(Dorbit.Framework.Send.SendByBaseNumber4Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.SendSms2Response> SendSms2Async(Dorbit.Framework.Send.SendSms2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSMSQueueDeliveries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.GetSMSQueueDeliveriesResponse> GetSMSQueueDeliveriesAsync(Dorbit.Framework.Send.GetSMSQueueDeliveriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMultipleSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.SendMultipleSMSResponse> SendMultipleSMSAsync(Dorbit.Framework.Send.SendMultipleSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMultipleSMS2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.SendMultipleSMS2Response> SendMultipleSMS2Async(Dorbit.Framework.Send.SendMultipleSMS2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReceptionsRecID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<Dorbit.Framework.Send.GetReceptionsRecIDResponse> GetReceptionsRecIDAsync(Dorbit.Framework.Send.GetReceptionsRecIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSimpleSMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSimpleSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool isflash;
        
        public SendSimpleSMSRequest()
        {
        }
        
        public SendSimpleSMSRequest(string username, string password, string[] to, string from, string text, bool isflash)
        {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSimpleSMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSimpleSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] SendSimpleSMSResult;
        
        public SendSimpleSMSResponse()
        {
        }
        
        public SendSimpleSMSResponse(string[] SendSimpleSMSResult)
        {
            this.SendSimpleSMSResult = SendSimpleSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSimpleSMS2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSimpleSMS2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool isflash;
        
        public SendSimpleSMS2Request()
        {
        }
        
        public SendSimpleSMS2Request(string username, string password, string to, string from, string text, bool isflash)
        {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSimpleSMS2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSimpleSMS2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SendSimpleSMS2Result;
        
        public SendSimpleSMS2Response()
        {
        }
        
        public SendSimpleSMS2Response(string SendSimpleSMS2Result)
        {
            this.SendSimpleSMS2Result = SendSimpleSMS2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSms", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool isflash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string udh;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        public SendSmsRequest()
        {
        }
        
        public SendSmsRequest(string username, string password, string[] to, string from, string text, bool isflash, string udh, long[] recId, byte[] status)
        {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.udh = udh;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSmsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendSmsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        public SendSmsResponse()
        {
        }
        
        public SendSmsResponse(int SendSmsResult, long[] recId, byte[] status)
        {
            this.SendSmsResult = SendSmsResult;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendWithDomain", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendWithDomainRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool isflash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string domainName;
        
        public SendWithDomainRequest()
        {
        }
        
        public SendWithDomainRequest(string username, string password, string to, string from, string text, bool isflash, string domainName)
        {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.domainName = domainName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendWithDomainResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendWithDomainResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SendWithDomainResult;
        
        public SendWithDomainResponse()
        {
        }
        
        public SendWithDomainResponse(string SendWithDomainResult)
        {
            this.SendWithDomainResult = SendWithDomainResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSmsPrice", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSmsPriceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int irancellCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int mtnCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string text;
        
        public GetSmsPriceRequest()
        {
        }
        
        public GetSmsPriceRequest(string username, string password, int irancellCount, int mtnCount, string from, string text)
        {
            this.username = username;
            this.password = password;
            this.irancellCount = irancellCount;
            this.mtnCount = mtnCount;
            this.from = from;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSmsPriceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSmsPriceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double GetSmsPriceResult;
        
        public GetSmsPriceResponse()
        {
        }
        
        public GetSmsPriceResponse(double GetSmsPriceResult)
        {
            this.GetSmsPriceResult = GetSmsPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCredit", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCreditRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        public GetCreditRequest()
        {
        }
        
        public GetCreditRequest(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCreditResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCreditResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double GetCreditResult;
        
        public GetCreditResponse()
        {
        }
        
        public GetCreditResponse(double GetCreditResult)
        {
            this.GetCreditResult = GetCreditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDelivery", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDeliveryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long recId;
        
        public GetDeliveryRequest()
        {
        }
        
        public GetDeliveryRequest(long recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeliveryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDeliveryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetDeliveryResult;
        
        public GetDeliveryResponse()
        {
        }
        
        public GetDeliveryResponse(int GetDeliveryResult)
        {
            this.GetDeliveryResult = GetDeliveryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDelivery2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDelivery2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string recId;
        
        public GetDelivery2Request()
        {
        }
        
        public GetDelivery2Request(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDelivery2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDelivery2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetDelivery2Result;
        
        public GetDelivery2Response()
        {
        }
        
        public GetDelivery2Response(int GetDelivery2Result)
        {
            this.GetDelivery2Result = GetDelivery2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMultiDelivery", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMultiDeliveryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string recId;
        
        public GetMultiDeliveryRequest()
        {
        }
        
        public GetMultiDeliveryRequest(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMultiDeliveryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMultiDeliveryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetMultiDeliveryResult;
        
        public GetMultiDeliveryResponse()
        {
        }
        
        public GetMultiDeliveryResponse(byte[] GetMultiDeliveryResult)
        {
            this.GetMultiDeliveryResult = GetMultiDeliveryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMultiDelivery2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMultiDelivery2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string recId;
        
        public GetMultiDelivery2Request()
        {
        }
        
        public GetMultiDelivery2Request(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMultiDelivery2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMultiDelivery2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] GetMultiDelivery2Result;
        
        public GetMultiDelivery2Response()
        {
        }
        
        public GetMultiDelivery2Response(string[] GetMultiDelivery2Result)
        {
            this.GetMultiDelivery2Result = GetMultiDelivery2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeliveries", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDeliveriesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long[] recIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string password;
        
        public GetDeliveriesRequest()
        {
        }
        
        public GetDeliveriesRequest(long[] recIds, string username, string password)
        {
            this.recIds = recIds;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeliveriesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDeliveriesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int[] GetDeliveriesResult;
        
        public GetDeliveriesResponse()
        {
        }
        
        public GetDeliveriesResponse(int[] GetDeliveriesResult)
        {
            this.GetDeliveriesResult = GetDeliveriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeliveries2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDeliveries2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string recId;
        
        public GetDeliveries2Request()
        {
        }
        
        public GetDeliveries2Request(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeliveries2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDeliveries2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetDeliveries2Result;
        
        public GetDeliveries2Response()
        {
        }
        
        public GetDeliveries2Response(int GetDeliveries2Result)
        {
            this.GetDeliveries2Result = GetDeliveries2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeliveries3", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDeliveries3Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string password;
        
        public GetDeliveries3Request()
        {
        }
        
        public GetDeliveries3Request(string[] recId, string username, string password)
        {
            this.recId = recId;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeliveries3Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDeliveries3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int[] GetDeliveries3Result;
        
        public GetDeliveries3Response()
        {
        }
        
        public GetDeliveries3Response(int[] GetDeliveries3Result)
        {
            this.GetDeliveries3Result = GetDeliveries3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInboxCount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetInboxCountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool isRead;
        
        public GetInboxCountRequest()
        {
        }
        
        public GetInboxCountRequest(string username, string password, bool isRead)
        {
            this.username = username;
            this.password = password;
            this.isRead = isRead;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInboxCountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetInboxCountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetInboxCountResult;
        
        public GetInboxCountResponse()
        {
        }
        
        public GetInboxCountResponse(int GetInboxCountResult)
        {
            this.GetInboxCountResult = GetInboxCountResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessagesBL : BaseBL
    {
        
        private long msgIDField;
        
        private int userIDField;
        
        private int linkIDField;
        
        private int numberIDField;
        
        private double tariffField;
        
        private byte msgTypeField;
        
        private string bodyField;
        
        private string udhField;
        
        private System.DateTime sendDateField;
        
        private string senderField;
        
        private string receiverField;
        
        private int firstLocationField;
        
        private int currentLocationField;
        
        private int partsField;
        
        private bool isFlashField;
        
        private bool isReadField;
        
        private bool isUnicodeField;
        
        private double creditField;
        
        private int moduleField;
        
        private int recCountField;
        
        private int recFailedField;
        
        private int recSuccessField;
        
        private bool isMoneyBackField;
        
        private int userStepedMasterField;
        
        private int userMasterField;
        
        private int moneyBackCountField;
        
        private int moneyBackLevelField;
        
        private System.Nullable<bool> autoSpeechTextField;
        
        private System.Nullable<int> shareServiceBodyIDField;
        
        private System.Nullable<int> irancellBackCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long MsgID
        {
            get
            {
                return this.msgIDField;
            }
            set
            {
                this.msgIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int LinkID
        {
            get
            {
                return this.linkIDField;
            }
            set
            {
                this.linkIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int NumberID
        {
            get
            {
                return this.numberIDField;
            }
            set
            {
                this.numberIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double Tariff
        {
            get
            {
                return this.tariffField;
            }
            set
            {
                this.tariffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public byte MsgType
        {
            get
            {
                return this.msgTypeField;
            }
            set
            {
                this.msgTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Udh
        {
            get
            {
                return this.udhField;
            }
            set
            {
                this.udhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime SendDate
        {
            get
            {
                return this.sendDateField;
            }
            set
            {
                this.sendDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Receiver
        {
            get
            {
                return this.receiverField;
            }
            set
            {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int FirstLocation
        {
            get
            {
                return this.firstLocationField;
            }
            set
            {
                this.firstLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int CurrentLocation
        {
            get
            {
                return this.currentLocationField;
            }
            set
            {
                this.currentLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int Parts
        {
            get
            {
                return this.partsField;
            }
            set
            {
                this.partsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool IsFlash
        {
            get
            {
                return this.isFlashField;
            }
            set
            {
                this.isFlashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool IsRead
        {
            get
            {
                return this.isReadField;
            }
            set
            {
                this.isReadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool IsUnicode
        {
            get
            {
                return this.isUnicodeField;
            }
            set
            {
                this.isUnicodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public double Credit
        {
            get
            {
                return this.creditField;
            }
            set
            {
                this.creditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int Module
        {
            get
            {
                return this.moduleField;
            }
            set
            {
                this.moduleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int RecCount
        {
            get
            {
                return this.recCountField;
            }
            set
            {
                this.recCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int RecFailed
        {
            get
            {
                return this.recFailedField;
            }
            set
            {
                this.recFailedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int RecSuccess
        {
            get
            {
                return this.recSuccessField;
            }
            set
            {
                this.recSuccessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public bool IsMoneyBack
        {
            get
            {
                return this.isMoneyBackField;
            }
            set
            {
                this.isMoneyBackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int UserStepedMaster
        {
            get
            {
                return this.userStepedMasterField;
            }
            set
            {
                this.userStepedMasterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int UserMaster
        {
            get
            {
                return this.userMasterField;
            }
            set
            {
                this.userMasterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int MoneyBackCount
        {
            get
            {
                return this.moneyBackCountField;
            }
            set
            {
                this.moneyBackCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int MoneyBackLevel
        {
            get
            {
                return this.moneyBackLevelField;
            }
            set
            {
                this.moneyBackLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<bool> AutoSpeechText
        {
            get
            {
                return this.autoSpeechTextField;
            }
            set
            {
                this.autoSpeechTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<int> ShareServiceBodyID
        {
            get
            {
                return this.shareServiceBodyIDField;
            }
            set
            {
                this.shareServiceBodyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<int> IrancellBackCount
        {
            get
            {
                return this.irancellBackCountField;
            }
            set
            {
                this.irancellBackCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessagesBL))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseBL
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceptionsRecID
    {
        
        private long msgIDField;
        
        private long recIDField;
        
        private string bodyField;
        
        private System.DateTime sendDateField;
        
        private string senderField;
        
        private string receiverField;
        
        private byte recStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long MsgID
        {
            get
            {
                return this.msgIDField;
            }
            set
            {
                this.msgIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long RecID
        {
            get
            {
                return this.recIDField;
            }
            set
            {
                this.recIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime SendDate
        {
            get
            {
                return this.sendDateField;
            }
            set
            {
                this.sendDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Receiver
        {
            get
            {
                return this.receiverField;
            }
            set
            {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public byte RecStatus
        {
            get
            {
                return this.recStatusField;
            }
            set
            {
                this.recStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessages", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getMessagesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int location;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int index;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int count;
        
        public getMessagesRequest()
        {
        }
        
        public getMessagesRequest(string username, string password, int location, string from, int index, int count)
        {
            this.username = username;
            this.password = password;
            this.location = location;
            this.from = from;
            this.index = index;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessagesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getMessagesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Dorbit.Framework.Send.MessagesBL[] getMessagesResult;
        
        public getMessagesResponse()
        {
        }
        
        public getMessagesResponse(Dorbit.Framework.Send.MessagesBL[] getMessagesResult)
        {
            this.getMessagesResult = getMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendByBaseNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendByBaseNumberRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int bodyId;
        
        public SendByBaseNumberRequest()
        {
        }
        
        public SendByBaseNumberRequest(string username, string password, string[] text, string to, int bodyId)
        {
            this.username = username;
            this.password = password;
            this.text = text;
            this.to = to;
            this.bodyId = bodyId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendByBaseNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendByBaseNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SendByBaseNumberResult;
        
        public SendByBaseNumberResponse()
        {
        }
        
        public SendByBaseNumberResponse(string SendByBaseNumberResult)
        {
            this.SendByBaseNumberResult = SendByBaseNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendByBaseNumber2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendByBaseNumber2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int bodyId;
        
        public SendByBaseNumber2Request()
        {
        }
        
        public SendByBaseNumber2Request(string username, string password, string text, string to, int bodyId)
        {
            this.username = username;
            this.password = password;
            this.text = text;
            this.to = to;
            this.bodyId = bodyId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendByBaseNumber2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendByBaseNumber2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SendByBaseNumber2Result;
        
        public SendByBaseNumber2Response()
        {
        }
        
        public SendByBaseNumber2Response(string SendByBaseNumber2Result)
        {
            this.SendByBaseNumber2Result = SendByBaseNumber2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendByBaseNumber3", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendByBaseNumber3Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string to;
        
        public SendByBaseNumber3Request()
        {
        }
        
        public SendByBaseNumber3Request(string username, string password, string text, string to)
        {
            this.username = username;
            this.password = password;
            this.text = text;
            this.to = to;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendByBaseNumber3Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendByBaseNumber3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SendByBaseNumber3Result;
        
        public SendByBaseNumber3Response()
        {
        }
        
        public SendByBaseNumber3Response(string SendByBaseNumber3Result)
        {
            this.SendByBaseNumber3Result = SendByBaseNumber3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendByBaseNumber4", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendByBaseNumber4Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int bodyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public double smsPrice;
        
        public SendByBaseNumber4Request()
        {
        }
        
        public SendByBaseNumber4Request(string username, string password, string text, string to, int bodyId, double smsPrice)
        {
            this.username = username;
            this.password = password;
            this.text = text;
            this.to = to;
            this.bodyId = bodyId;
            this.smsPrice = smsPrice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendByBaseNumber4Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendByBaseNumber4Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SendByBaseNumber4Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public double smsPrice;
        
        public SendByBaseNumber4Response()
        {
        }
        
        public SendByBaseNumber4Response(string SendByBaseNumber4Result, double smsPrice)
        {
            this.SendByBaseNumber4Result = SendByBaseNumber4Result;
            this.smsPrice = smsPrice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSms2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSms2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool isflash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string udh;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public int filterId;
        
        public SendSms2Request()
        {
        }
        
        public SendSms2Request(string username, string password, string[] to, string from, string text, bool isflash, string udh, long[] recId, byte[] status, int filterId)
        {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.udh = udh;
            this.recId = recId;
            this.status = status;
            this.filterId = filterId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSms2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSms2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendSms2Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int filterId;
        
        public SendSms2Response()
        {
        }
        
        public SendSms2Response(int SendSms2Result, long[] recId, byte[] status, int filterId)
        {
            this.SendSms2Result = SendSms2Result;
            this.recId = recId;
            this.status = status;
            this.filterId = filterId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSMSQueueDeliveries", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSMSQueueDeliveriesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long[] Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string password;
        
        public GetSMSQueueDeliveriesRequest()
        {
        }
        
        public GetSMSQueueDeliveriesRequest(long[] Id, string username, string password)
        {
            this.Id = Id;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSMSQueueDeliveriesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSMSQueueDeliveriesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int[] GetSMSQueueDeliveriesResult;
        
        public GetSMSQueueDeliveriesResponse()
        {
        }
        
        public GetSMSQueueDeliveriesResponse(int[] GetSMSQueueDeliveriesResult)
        {
            this.GetSMSQueueDeliveriesResult = GetSMSQueueDeliveriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMultipleSMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMultipleSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string[] text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool isflash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string udh;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        public SendMultipleSMSRequest()
        {
        }
        
        public SendMultipleSMSRequest(string username, string password, string[] to, string from, string[] text, bool isflash, string udh, long[] recId, byte[] status)
        {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.udh = udh;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMultipleSMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMultipleSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int[] SendMultipleSMSResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        public SendMultipleSMSResponse()
        {
        }
        
        public SendMultipleSMSResponse(int[] SendMultipleSMSResult, long[] recId, byte[] status)
        {
            this.SendMultipleSMSResult = SendMultipleSMSResult;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMultipleSMS2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMultipleSMS2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string[] text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool isflash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string udh;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        public SendMultipleSMS2Request()
        {
        }
        
        public SendMultipleSMS2Request(string username, string password, string[] to, string[] from, string[] text, bool isflash, string udh, long[] recId, byte[] status)
        {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.udh = udh;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMultipleSMS2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMultipleSMS2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int[] SendMultipleSMS2Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        public SendMultipleSMS2Response()
        {
        }
        
        public SendMultipleSMS2Response(int[] SendMultipleSMS2Result, long[] recId, byte[] status)
        {
            this.SendMultipleSMS2Result = SendMultipleSMS2Result;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReceptionsRecID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetReceptionsRecIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime dateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.DateTime dateTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int index;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int count;
        
        public GetReceptionsRecIDRequest()
        {
        }
        
        public GetReceptionsRecIDRequest(string username, string password, System.DateTime dateFrom, System.DateTime dateTo, int index, int count)
        {
            this.username = username;
            this.password = password;
            this.dateFrom = dateFrom;
            this.dateTo = dateTo;
            this.index = index;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReceptionsRecIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetReceptionsRecIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Dorbit.Framework.Send.ReceptionsRecID[] GetReceptionsRecIDResult;
        
        public GetReceptionsRecIDResponse()
        {
        }
        
        public GetReceptionsRecIDResponse(Dorbit.Framework.Send.ReceptionsRecID[] GetReceptionsRecIDResult)
        {
            this.GetReceptionsRecIDResult = GetReceptionsRecIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface SendSoapChannel : Dorbit.Framework.Send.SendSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SendSoapClient : System.ServiceModel.ClientBase<Dorbit.Framework.Send.SendSoap>, Dorbit.Framework.Send.SendSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SendSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SendSoapClient.GetBindingForEndpoint(endpointConfiguration), SendSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SendSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SendSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.SendSimpleSMSResponse> SendSimpleSMSAsync(Dorbit.Framework.Send.SendSimpleSMSRequest request)
        {
            return base.Channel.SendSimpleSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.SendSimpleSMS2Response> SendSimpleSMS2Async(Dorbit.Framework.Send.SendSimpleSMS2Request request)
        {
            return base.Channel.SendSimpleSMS2Async(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.SendSmsResponse> SendSmsAsync(Dorbit.Framework.Send.SendSmsRequest request)
        {
            return base.Channel.SendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.SendWithDomainResponse> SendWithDomainAsync(Dorbit.Framework.Send.SendWithDomainRequest request)
        {
            return base.Channel.SendWithDomainAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.GetSmsPriceResponse> GetSmsPriceAsync(Dorbit.Framework.Send.GetSmsPriceRequest request)
        {
            return base.Channel.GetSmsPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.GetCreditResponse> GetCreditAsync(Dorbit.Framework.Send.GetCreditRequest request)
        {
            return base.Channel.GetCreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.GetDeliveryResponse> GetDeliveryAsync(Dorbit.Framework.Send.GetDeliveryRequest request)
        {
            return base.Channel.GetDeliveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.GetDelivery2Response> GetDelivery2Async(Dorbit.Framework.Send.GetDelivery2Request request)
        {
            return base.Channel.GetDelivery2Async(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.GetMultiDeliveryResponse> GetMultiDeliveryAsync(Dorbit.Framework.Send.GetMultiDeliveryRequest request)
        {
            return base.Channel.GetMultiDeliveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.GetMultiDelivery2Response> GetMultiDelivery2Async(Dorbit.Framework.Send.GetMultiDelivery2Request request)
        {
            return base.Channel.GetMultiDelivery2Async(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.GetDeliveriesResponse> GetDeliveriesAsync(Dorbit.Framework.Send.GetDeliveriesRequest request)
        {
            return base.Channel.GetDeliveriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.GetDeliveries2Response> GetDeliveries2Async(Dorbit.Framework.Send.GetDeliveries2Request request)
        {
            return base.Channel.GetDeliveries2Async(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.GetDeliveries3Response> GetDeliveries3Async(Dorbit.Framework.Send.GetDeliveries3Request request)
        {
            return base.Channel.GetDeliveries3Async(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.GetInboxCountResponse> GetInboxCountAsync(Dorbit.Framework.Send.GetInboxCountRequest request)
        {
            return base.Channel.GetInboxCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.getMessagesResponse> getMessagesAsync(Dorbit.Framework.Send.getMessagesRequest request)
        {
            return base.Channel.getMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.SendByBaseNumberResponse> SendByBaseNumberAsync(Dorbit.Framework.Send.SendByBaseNumberRequest request)
        {
            return base.Channel.SendByBaseNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.SendByBaseNumber2Response> SendByBaseNumber2Async(Dorbit.Framework.Send.SendByBaseNumber2Request request)
        {
            return base.Channel.SendByBaseNumber2Async(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.SendByBaseNumber3Response> SendByBaseNumber3Async(Dorbit.Framework.Send.SendByBaseNumber3Request request)
        {
            return base.Channel.SendByBaseNumber3Async(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.SendByBaseNumber4Response> SendByBaseNumber4Async(Dorbit.Framework.Send.SendByBaseNumber4Request request)
        {
            return base.Channel.SendByBaseNumber4Async(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.SendSms2Response> SendSms2Async(Dorbit.Framework.Send.SendSms2Request request)
        {
            return base.Channel.SendSms2Async(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.GetSMSQueueDeliveriesResponse> GetSMSQueueDeliveriesAsync(Dorbit.Framework.Send.GetSMSQueueDeliveriesRequest request)
        {
            return base.Channel.GetSMSQueueDeliveriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.SendMultipleSMSResponse> SendMultipleSMSAsync(Dorbit.Framework.Send.SendMultipleSMSRequest request)
        {
            return base.Channel.SendMultipleSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.SendMultipleSMS2Response> SendMultipleSMS2Async(Dorbit.Framework.Send.SendMultipleSMS2Request request)
        {
            return base.Channel.SendMultipleSMS2Async(request);
        }
        
        public System.Threading.Tasks.Task<Dorbit.Framework.Send.GetReceptionsRecIDResponse> GetReceptionsRecIDAsync(Dorbit.Framework.Send.GetReceptionsRecIDRequest request)
        {
            return base.Channel.GetReceptionsRecIDAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SendSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SendSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SendSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://api.payamak-panel.com/post/send.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SendSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://api.payamak-panel.com/post/send.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SendSoap,
            
            SendSoap12,
        }
    }
}
